### Updated: 07/15/2026

#!/usr/bin/env python3
"""
pipeline_immunity_genes.py
 
Runs a BLASTp search against the rotifer protein database, then extracts
the matching sequences using the lab's extract_sequences.py script.
 
Works on a single query file OR a folder of query files (one gene each).
 
Single file:
    python3 pipeline_immunity_genes.py -q DEFB_BLAST1.fa
 
Multiple genes:
    python3 pipeline_immunity_genes.py --query-dir my_genes/
 
Run in background:
    nohup python3 pipeline_immunity_genes.py --query-dir my_genes/ &
"""
 
import argparse
import subprocess
import sys
import os
import glob
 
# --------------------------------------------------------------------------
# Configuration
# --------------------------------------------------------------------------


 
BLASTP_BIN = "/usr/local/ncbi-blast-2.16.0/bin/blastp"
 
ROTIFER_DB = "/data/references/rotifer/2026/rotifer_proteins"

# Reference FASTA file containing all rotifer protein sequences.
# Used by extract_sequences.py to retrieve the sequences matching the BLAST hits.

 
ROTIFER_FASTA = "/data/references/rotifer/2026/rotifer_proteins_20260422.fasta"
 
EXTRACT_SCRIPT = "/data/mohl_lab/scripts/extract_sequences.py"
 
 
def run_blast(query, db, out, threads, evalue):
    """
    Run BLASTp on a single query FASTA file.
    """
 
    outfmt = (
        "6 qseqid qtitle sseqid stitle bitscore "
        "qcovs evalue pident slen length qlen mismatch"
    )
 
    cmd = [
        BLASTP_BIN,
        "-query", query,
        "-db", db,
        "-out", out,
        "-num_threads", str(threads),
        "-evalue", str(evalue),
        "-outfmt", outfmt,
    ]
 
    print(f"[1/3] Running BLASTp on {query} ...")
    print(" ", " ".join(cmd), "\n")
 
    result = subprocess.run(cmd)
 
    if result.returncode != 0:
        print(f"BLASTp exited with error code {result.returncode}")
        sys.exit(result.returncode)
 
    print(f"BLASTp finished. Output written to {out}\n")
 
 
def get_hit_ids(blast_out):
    """
    Extract the unique rotifer sequence IDs from the BLAST output.
    """
 
    ids = set()
 
    with open(blast_out) as f:
        for line in f:
 
            parts = line.strip().split("\t")
 
            if len(parts) > 1:
                ids.add(parts[1].strip())
 
    print(f"[2/3] Found {len(ids)} unique hit IDs\n")
 
    return sorted(ids)
 
 
def run_extract(blast_out, ids, extracted_out):
    """
    Run extract_sequences.py using the list of BLAST hit IDs.
    """
 
    tmp_list = extracted_out + ".tmp_ids.txt"
 
    # Write the unique rotifer sequence IDs to a temporary file.
    # This file serves as input for extract_sequences.py.

    with open(tmp_list, "w") as f:
        for id_ in ids:
            f.write(id_ + "\n")
    

    # Run the extraction script using:
    #   1. The rotifer protein FASTA database
    #   2. The list of matching rotifer sequence IDs
    #   3. The output file prefix
   
    cmd = [
        "python3",
        EXTRACT_SCRIPT,
        ROTIFER_FASTA,
        tmp_list,
        extracted_out,
    ]
 
    print("[3/3] Extracting sequences...")
    print(" ", " ".join(cmd), "\n")
 
    # Capture standard output and error messages generated by the extraction script.

    result = subprocess.run(
        cmd,
        capture_output=True,
        text=True
    )
 
    # Display status messages and errors returned by the extraction script.

    if result.stdout:
        print(result.stdout)
 
    if result.stderr:
        print(result.stderr)
 
    # Remove the temporary ID file after the extraction completes successfully.

    if result.returncode != 0:
        print(f"extract_sequences.py exited with error code {result.returncode}")
        sys.exit(result.returncode)
 
    os.remove(tmp_list)
 
    print(f"Extraction finished. Output written to {extracted_out}\n")
 
 
def process_one(query, db, out, extracted, threads, evalue):
    """
    Process a single query FASTA file through the pipeline.
    """
 
    if not os.path.isfile(query):
        print(f"Error: query file '{query}' not found.")
        return
 
    run_blast(query, db, out, threads, evalue)
 
    if not os.path.isfile(out) or os.path.getsize(out) == 0:
        print(
            f"Warning: BLAST output '{out}' is empty "
            f"(evalue={evalue})."
        )
        print("Skipping extraction.\n")
        return
 
    ids = get_hit_ids(out)
 
    if not ids:
        print(f"No hit IDs found for {query}. Skipping.\n")
        return
 
    run_extract(out, ids, extracted)
 
 
 
 
 
def main():
    """
    Parse command-line arguments and process one or more query FASTA files.
    """
 
    parser = argparse.ArgumentParser(
        description=(
            "Run BLASTp against the rotifer protein database, "
            "then extract matching sequences."
        )
    )
 
    parser.add_argument(
        "-q",
        "--query",
        default=None,
        help="Single input FASTA query file"
    )
 
    parser.add_argument(
        "--query-dir",
        default=None,
        help="Directory containing FASTA query files"
    )
 
    parser.add_argument(
        "-d",
        "--db",
        default=ROTIFER_DB,
        help="Path to the BLAST database"
    )
 
    parser.add_argument(
        "-t",
        "--threads",
        type=int,
        default=30,
        help="Number of BLAST threads"
    )
 
    parser.add_argument(
        "--evalue",
        default="0.001",
        help="BLAST E-value threshold"
    )
 
    parser.add_argument(
        "--output-dir",
        default=".",
        help="Directory where output files will be written"
    )
 
    args = parser.parse_args()
 
    # If no query file or directory is provided, use the current working directory.

    if not args.query and not args.query_dir:
        args.query = os.getcwd()
 
    os.makedirs(args.output_dir, exist_ok=True)
 
    # ----------------------------------------------------------------------
    # Process a single query
    # ----------------------------------------------------------------------
    if args.query:
 
        gene = os.path.splitext(os.path.basename(args.query))[0]
 
        out = os.path.join(
            args.output_dir,
            f"{gene}_ROT_BLAST.out"
        )
 
        extracted = os.path.join(
            args.output_dir,
            f"extracted_{gene}"
        )
 
        process_one(
            args.query,
            args.db,
            out,
            extracted,
            args.threads,
            args.evalue
        )
 
    # ----------------------------------------------------------------------
    # Process every FASTA file in the input directory
    # ----------------------------------------------------------------------
    else:
 
        patterns = ["*.fa", "*.fasta", "*.txt"]
 
        fasta_files = sorted(
            set(
                f
                for pattern in patterns
                for f in glob.glob(os.path.join(args.query_dir, pattern))
            )
        )
 
        if not fasta_files:
            print(f"No .fa/.fasta/.txt files found in {args.query_dir}")
            sys.exit(1)
 
        print(f"\nFound {len(fasta_files)} query file(s).\n")
 
        for query in fasta_files:
 
            gene = os.path.splitext(os.path.basename(query))[0]
 
            print("\n" + "=" * 60)
            print(f"Processing gene: {gene}")
            print("=" * 60)
 
            out = os.path.join(
                args.output_dir,
                f"{gene}_ROT_BLAST.out"
            )
 
            extracted = os.path.join(
                args.output_dir,
                f"extracted_{gene}"
            )
 
            process_one(
                query,
                args.db,
                out,
                extracted,
                args.threads,
                args.evalue
            )
 
            # Print a separator after processing each query gene.
            print(f"Finished processing {gene}\n")
 
    print("=" * 60)
    print("Pipeline complete.")
    print("=" * 60)
 
 
if __name__ == "__main__":
    main()
